[WIP] Highwinds Certificates service
openwurl/wurlwind pull request #3
Opened 2019-09-09 19:29 UTC by asciifaceman

# Certificates

TLS certificate management

# Endpoints

```
GET /api/v1/accounts/{account_hash}/certificates List all certificates on an account
POST /api/v1/accounts/{account_hash}/certificates Upload a new certificate
DELETE /api/v1/accounts/{account_hash}/certificates/{certificate_id} Delete a certificate
GET /api/v1/accounts/{account_hash}/certificates/{certificate_id} Get a certificate
PUT /api/v1/accounts/{account_hash}/certificates/{certificate_id} Update a certificate (useful for expired certs)
GET/api/v1/accounts/{account_hash}/certificates/{certificate_id}/hosts Get Hosts for Certificate
```

2019-09-12 22:02 UTC, asciifaceman commented
@apsoto requested a review but might be minor small changes in the pipeline

2019-09-13 05:39 UTC, apsoto requested changes

2019-09-13 05:39 UTC, apsoto commented on Makefile
> +INTEGRATIONBUNDLE?=
I'm a fan of separating words with `_` or `-` for readability.

2019-09-13 05:39 UTC, apsoto commented on pkg/fileio/fileio.go
> +}
minor quibble, but a whole method/package for basically a type cast?

2019-09-13 05:39 UTC, apsoto commented on pkg/integration/integration.go
> +	}
If it's invalid if any of the key,cert,or bundle is missing, it seems like you could short circuit sooner, by exiting with error as soon as you find a missing one, and it keeps the check/error for an item with the loading logic for the particular item.

2019-09-13 05:39 UTC, apsoto commented on pkg/integration/integration.go
> +}
This function isn't referenced, except in commented out code above.  Also, seems a little bit strange to have a getter also return an error if the parameter `evar` is not present when there is such a short list of expected env vars.  I suppose if there was a comment doc it would be less strange.

2019-09-13 05:39 UTC, apsoto commented on striketracker/errors.go
> +)
I suppose this is copied/generated directly from strike tracker documentation?  Maybe put a link to it.

2019-09-13 05:39 UTC, apsoto commented on striketracker/services/certificates/certificates.go
>  func (s *Service) Upload(ctx context.Context, accountHash string, certificate *models.Certificate) (*models.Certificate, error) {
I typically map CRUD to HTTP Verbs for a RESTful API and consider a POST a Create (as opposed to Upload).

2019-09-13 06:17 UTC, asciifaceman commented on striketracker/services/certificates/certificates.go
>  func (s *Service) Upload(ctx context.Context, accountHash string, certificate *models.Certificate) (*models.Certificate, error) {
In this case, it's their nomenclature and not mine. I'm mapping to their names - but I feel ya

2019-09-13 06:18 UTC, asciifaceman commented on striketracker/errors.go
> +)
The link is unfortunately behind an authorization wall, and it's also just this (no extra information)

2019-09-13 06:20 UTC, asciifaceman commented on Makefile
> +INTEGRATIONBUNDLE?=
ignore these, there is something wonky I have to work out for certificates to support long term integration testing on the certificate API 

these will be changed once I figure that out

2019-09-13 06:20 UTC, asciifaceman commented on pkg/fileio/fileio.go
> +}
one that gets repeated in a few places  ;) 

but yes

2019-09-13 06:24 UTC, asciifaceman commented on pkg/integration/integration.go
> +}
This is a vestigial  function that is no longer in use, as you mentioned. 

But I wanted to address that having an error in a return for a getter in this case was being used to short circuit logic.

But as you can see that was half written before I went with the other mechanism above.

2019-09-13 06:27 UTC, asciifaceman commented on pkg/integration/integration.go
> +	}
I just realized this is literally what Validate() is for since I have a cert object.

2019-09-13 06:29 UTC, asciifaceman commented on striketracker/services/certificates/certificates.go
>  func (s *Service) Upload(ctx context.Context, accountHash string, certificate *models.Certificate) (*models.Certificate, error) {
I think in this particular case it's because you don't "Create" a certificate in Highwinds, that has a very different meaning semantically. It would imply they made one. Instead, you are uploading an existing one.

2019-09-13 06:32 UTC, asciifaceman commented on Makefile
> +INTEGRATIONBUNDLE?=
commented out for now

2019-09-13 06:32 UTC, asciifaceman commented on pkg/fileio/fileio.go
> +}
I'm holding on to this for right now as it might be expanded on, will re-review in a few PRs

2019-09-13 06:32 UTC, asciifaceman commented on pkg/integration/integration.go
> +}
terminated

2019-09-13 06:34 UTC, asciifaceman commented
Not to short circuit the process, but I'm going to go ahead and merge this @apsoto because I need it in master tomorrow morning so I can prepare demo stuff

I've addressed a few things and others are being shelved  for now

2019-09-13 06:35 UTC, merged